export const HANDLE_MODAL_POST_DETAIL = "HANDLE_MODAL_POST_DETAIL"
export const HANDLE_ADD_POST = "HANDLE_ADD_POST"
export const HANDLE_GET_POST = "HANDLE_GET_POST"

export const HANDLE_ADD_COMMENT = "HANDLE_ADD_COMMENT"
export const HANDLE_ADD_REMOVE_LOVE = "HANDLE_ADD_REMOVE_LOVE"